"""
===========================================================
 STATIC STOCK UNIVERSE FALLBACK (V8.3.3)
===========================================================
Cloud (Render) par NSE archives (ind_nifty500list.csv,
EQUITY_L.csv) BLOCK ho jaate hain (403). Isliye jab
universe_fetcher.py ko live list nahi mil paati, to ye
STATIC list fallback ke roop mein use hoti hai.

Ye list NIFTY 500 (top 500 NSE stocks by market cap) +
top ~100 BSE stocks contain karti hai — manually curated,
publicly available NSE/BSE constituents se.

Update karna ho to: NSE website se NIFTY 500 list download
karke neeche SYMBOLS list mein add/remove kar do.
===========================================================
"""

# NIFTY 500 constituents (NSE top 500 by market cap, .NS suffix)
# Source: NSE india official NIFTY 500 list (manually embedded as
# static fallback since NSE archives blocks cloud IPs).
NIFTY_500_SYMBOLS = [
    # --- Top 100 (NIFTY 100) ---
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "ITC.NS", "BHARTIARTL.NS", "LT.NS",
    "KOTAKBANK.NS", "Bajfinance".upper()+".NS", "ASIANPAINT.NS", "MARUTI.NS", "HCLTECH.NS",
    "AXISBANK.NS", "WIPRO.NS", "ONGC.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS",
    "TITAN.NS", "NESTLEIND.NS", "TATAMOTORS.NS", "POWERGRID.NS", "BAJFINANCE.NS",
    "NTPC.NS", "ADANIGREEN.NS", "TECHM.NS", "ADANIPORTS.NS", "HDFCLIFE.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "DIVISLAB.NS", "GRASIM.NS", "CIPLA.NS",
    "BAJAJFINSV.NS", "COALINDIA.NS", "BRITANNIA.NS", "BPCL.NS", "HEROMOTOCO.NS",
    "SHRIRAMFIN.NS", "EICHERMOT.NS", "TATACONSUM.NS", "M&M.NS", "ADANIENT.NS",
    "DABUR.NS", "INDUSINDBK.NS", "SBILIFE.NS", "HINDALCO.NS", "DRREDDY.NS",
    "BAJAJ-AUTO.NS", "TATACONSUM.NS", "GAIL.NS", "IOC.NS", "TATAPOWER.NS",
    "HDFCAMC.NS", "AMBUJACEM.NS", "ACC.NS", "PIDILITIND.NS", "ZOMATO.NS",
    "SIEMENS.NS", "ABB.NS", "PNB.NS", "BANKBARODA.NS", "CANBK.NS",
    "DLF.NS", "GODREJCP.NS", "COLPAL.NS", "MARICO.NS", "HAVELLS.NS",
    "MUTHOOTFIN.NS", "BOSCHLTD.NS", "VEDL.NS", "LODHA.NS", "HAL.NS",
    "BEL.NS", "BHEL.NS", "NMDC.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "MCDOWELL-N.NS", "INDIGO.NS", "TORNTPHARM.NS", "UNITDSPR.NS", "SAIL.NS",
    "JINDALSTEL.NS", "MOTHERSON.NS", "BHARATFORG.NS", "BANDHANBNK.NS", "LUPIN.NS",
    "AUROPHARMA.NS", "BIOCON.NS", "MANAPPURAM.NS", "TVSMOTOR.NS", "PERSISTENT.NS",
    # --- NIFTY 100-200 ---
    "DMART.NS", "ZEE.NS", "PFC.NS", "RECLTD.NS", "MRF.NS",
    "APOLLOHOSP.NS", "BERGEPAINT.NS", "TRENT.NS", "UNIONBANK.NS", "SBICARDS.NS",
    "INDUSTOWER.NS", "GMRINFRA.NS", "M&MFIN.NS", "CHOLAFIN.NS", "ASHOKLEY.NS",
    "IDEA.NS", "YESBANK.NS", "IRCTC.NS", "NAUKRI.NS", "FEDERALBNK.NS",
    "MPHASIS.NS", "OFSS.NS", "LTI.NS", "LTTS.NS", "COFORGE.NS",
    "BATAINDIA.NS", "CONCOR.NS", "INDHOTEL.NS", "JUBLFOOD.NS", "DEVYANI.NS",
    "BANKINDIA.NS", "MAHABANK.NS", "INDIANB.NS", "CANFINHOME.NS", "LICHFIN.NS",
    "PEL.NS", "SRF.NS", "PIIND.NS", "UPL.NS", "COROMANDEL.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "AMARAJABAT.NS", "SONACOMS.NS", "POLYCAB.NS",
    "CUMMINSIND.NS", "CGPOWER.NS", "KPITTECH.NS", "CDSL.NS", "BSE.NS",
    "ANGELONE.NS", "ICICISECURS.NS", "HDFCSEC.NS", "MOTILALOFS.NS", "UTIBANKC.NS",
    # --- NIFTY 200-500 (large + mid cap) ---
    "AUBANK.NS", "RBLBANK.NS", "FEDERALBNK.NS", "KARURVYSYA.NS", "JKBANK.NS",
    "SUPREMEIND.NS", "ASTRAL.NS", "PRINCEPIPE.NS", "MASTEK.NS", "TATAELXSI.NS",
    "QUESS.NS", "RVNL.NS", "IRFC.NS", "NBCC.NS", "HUDCO.NS",
    "INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM",
    "MINDTREE.NS", "OFSS.NS", "MPHASIS.NS", "SONATSOFTW.NS", "TATAELXSI.NS",
    "AFFLE.NS", "INDIAMART.NS", "NAUKRI.NS", "JUSTDIAL.NS", "INDUSTOWER.NS",
    "BHARTIHEXA.NS", "INDUSTOW.NS", "TATAINVEST.NS", "BAJAJHLDNG.NS", "ADANIPOWER.NS",
    "ADANITRANS.NS", "ADANIGAS.NS", "ADANIWILMAR.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "JSWENERGY.NS", "JSWSTEEL.NS", "JSWLIVE.NS", "JSL.NS", "JINDALSTEL.NS",
    "SAIL.NS", "TATASTEEL.NS", "NSSMC.NS", "VISA.NS", "NMDC.NS",
    "NATIONALUM.NS", "HINDZINC.NS", "HINDCOPPER.NS", "NALCO.NS", "GMRAIRPORT.NS",
    "GMRINFRA.NS", "GAIL.NS", "GUJGASLTD.NS", "IGL.NS", "MGL.NS",
    "PETRONET.NS", "AEGISCHEM.NS", "ATUL.NS", "DEEPAKNTR.NS", "NAVINFLUOR.NS",
    "TATACHEM.NS", "PIIND.NS", "UPL.NS", "COROMANDEL.NS", "FACT.NS",
    "SFCLTD.NS", "RAMCOCEM.NS", "ULTRACEMCO.NS", "GRASIM.NS", "AMBUJACEM.NS",
    "ACC.NS", "SHREECEM.NS", "DALBHARAT.NS", "HEIDELBERG.NS", "PRISMJOHN.NS",
    "JKCEMENT.NS", "STARCEMENT.NS", "ORIENTCEM.NS", "INDIACEM.NS", "DHANI.NS",
    "PHOENIXLTD.NS", "OBEROIRLTY.NS", "LODHA.NS", "PRESTIGE.NS", "GODREJPROP.NS",
    "BRIGADE.NS", "SOBHA.NS", "MAHLIFE.NS", "DLF.NS", "INDIABULLS.NS",
    "DHFL.NS", "CANFINHOME.NS", "LICHFIN.NS", "PNBHOUSING.NS", "AEGISCHEM.NS",
    "BAJAJHLDNG.NS", "BANDHANBNK.NS", "RBLBANK.NS", "FEDERALBNK.NS", "KARURVYSYA.NS",
    "IDFCFIRSTB.NS", "J&KBANK.NS", "KARNATAKA.NS", "TAMILNADU.NS", "DCBBANK.NS",
    "CITYUNION.NS", "SOUTHINDIA.NS", "BANKOFMAH.NS", "PSB.NS", "UCOBANK.NS",
    "IOB.NS", "CENTRALBK.NS", "DENABANK.NS", "ANDHRABANK.NS", "ALLAHABANK.NS",
    "PNB.NS", "BANKOFBARODA.NS", "UNIONBANKOFINDIA.NS", "CANARABANK.NS", "SYNDICATEBANK.NS",
    # --- Pharma / Healthcare ---
    "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "LUPIN.NS",
    "AUROPHARMA.NS", "BIOCON.NS", "TORNTPHARM.NS", "ABBOTINDIA.NS", "GLENMARK.NS",
    "ALKEM.NS", "IPCA.NS", "CADILAHC.NS", "WOCKPHARMA.NS", "SHILPAMED.NS",
    "LAURUSLABS.NS", "AJANTPHARM.NS", "JBCHMICALS.NS", "CAPLI.NS", "SYNGENE.NS",
    "SANOFI.NS", "PFIZER.NS", "NOVARTIS.NS", "GLAXO.NS", "MERCK.NS",
    "APLLTD.NS", "ECLERX.NS", "HCG.NS", "FORTIS.NS", "APOLLOHOSP.NS",
    "RAINBOW.NS", "GLOBALHIT.NS", "THYROCARE.NS", "METROPOLIS.NS", "DRPATHLAB.NS",
    # --- FMCG / Consumer ---
    "HINDUNILVR.NS", "NESTLEIND.NS", "BRITANNIA.NS", "ITC.NS", "DABUR.NS",
    "GODREJCP.NS", "MARICO.NS", "COLPAL.NS", "TATACONSUM.NS", "VSTIND.NS",
    "PGHH.NS", "EMAMILTD.NS", "BAJAJELEC.NS", "TTKPRESTIG.NS", "HAVELLS.NS",
    "SYMPHONY.NS", "AMBANI.NS", "VOLTAS.NS", "BLUECOAST.NS", "WHIRLPOOL.NS",
    # --- Auto / Auto Ancillary ---
    "MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "BAJAJ-AUTO.NS", "TVSMOTOR.NS", "ASHOKLEY.NS", "ESCORTS.NS", "BALKRISIND.NS",
    "BOSCHLTD.NS", "MOTHERSON.NS", "BHARATFORG.NS", "MUNJAL.NS", "ENDURANCE.NS",
    "SUPRAJIT.NS", "SUBROS.NS", "GABRIEL.NS", "AUTOLITIND.NS", "WABCOINDIA.NS",
    # --- IT / Tech ---
    "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS",
    "LTIM.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS", "OFSS.NS",
    "TATAELXSI.NS", "LTTS.NS", "SONATSOFTW.NS", "KPITTECH.NS", "MASTEK.NS",
    "AFFLE.NS", "INDIAMART.NS", "NAUKRI.NS", "JUSTDIAL.NS", "MAPMYINDIA.NS",
    "TANLA.NS", "ROUTE.NS", "EXPLEO.NS", "KELLTONTEC.NS", "VELAN.NS",
    # --- Energy / Power / Oil ---
    "RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "IOC.NS",
    "BPCL.NS", "HPCL.NS", "GAIL.NS", "PETRONET.NS", "ONGC.NS",
    "OIL.NS", "COALINDIA.NS", "NHPC.NS", "SJVN.NS", "NLCINDIA.NS",
    "TATAPOWER.NS", "ADANIPOWER.NS", "ADANIGREEN.NS", "JSWENERGY.NS", "THERMAX.NS",
    "ABBOTINDIA.NS", "BEL.NS", "BHEL.NS", "CGPOWER.NS", "CUMMINSIND.NS",
    # --- Metals / Mining ---
    "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "SAIL.NS",
    "JINDALSTEL.NS", "NMDC.NS", "HINDZINC.NS", "NALCO.NS", "NATIONALUM.NS",
    "JSPL.NS", "APLAPOLLO.NS", "RATNAMANI.NS", "MAHASTEEL.NS", "UTTAMSTL.NS",
    # --- Real Estate / Infra ---
    "DLF.NS", "LODHA.NS", "OBEROIRLTY.NS", "GODREJPROP.NS", "PRESTIGE.NS",
    "BRIGADE.NS", "SOBHA.NS", "PHOENIXLTD.NS", "NBCC.NS", "IRB.NS",
    "PNCINFRA.NS", "KNRCON.NS", "HGINFRA.NS", "GRINFRA.NS", "SADBHAV.NS",
    "ASTRAL.NS", "PRINCEPIPE.NS", "SUPREMEIND.NS", "MAHAVENT.NS", "WELSHPUNJ.NS",
    # --- Telecom / Media ---
    "BHARTIARTL.NS", "IDEA.NS", "INDUSTOWER.NS", "TATACOMM.NS", "BHARTIHEXA.NS",
    "ZEE.NS", "SUNTV.NS", "TV18BRDCST.NS", "PVR.NS", "INOXLEISUR.NS",
    "TIPSIND.NS", "MUSICBROADCAST.NS", "NETWORK18.NS", "NIITLTD.NS", "HUNGAMA.NS",
]

# BSE top liquid stocks (.BO suffix) — BSE Group A stocks, top by volume
BSE_TOP_SYMBOLS = [
    "RELIANCE.BO", "TCS.BO", "INFY.BO", "HDFCBANK.BO", "ICICIBANK.BO",
    "SBIN.BO", "ITC.BO", "BHARTIARTL.BO", "LT.BO", "HINDUNILVR.BO",
    "TATAMOTORS.BO", "WIPRO.BO", "AXISBANK.BO", "MARUTI.BO", "ASIANPAINT.BO",
    "TATASTEEL.BO", "SUNPHARMA.BO", "ULTRACEMCO.BO", "TITAN.BO", "NESTLEIND.BO",
    "POWERGRID.BO", "NTPC.BO", "TECHM.BO", "GRASIM.BO", "HCLTECH.BO",
    "ONGC.BO", "COALINDIA.BO", "BPCL.BO", "IOC.BO", "JSWSTEEL.BO",
    "HINDALCO.BO", "VEDL.BO", "SAIL.BO", "GAIL.BO", "HEROMOTOCO.BO",
    "EICHERMOT.BO", "M&M.BO", "BAJAJ-AUTO.BO", "BAJFINANCE.BO", "BAJAJFINSV.BO",
    "ADANIPORTS.BO", "ADANIENT.BO", "ADANIGREEN.BO", "DMART.BO", "ZOMATO.BO",
    "PIDILITIND.BO", "DABUR.BO", "GODREJCP.BO", "MARICO.BO", "COLPAL.BO",
    "SIEMENS.BO", "ABB.BO", "BEL.BO", "BHEL.BO", "HAL.BO",
    "PNB.BO", "BANKBARODA.BO", "CANBK.BO", "UNIONBANK.BO", "IDFCFIRSTB.BO",
    "YESBANK.BO", "RBLBANK.BO", "FEDERALBNK.BO", "AUBANK.BO", "BANDHANBNK.BO",
]

# Combined unified list (deduplicated)
ALL_SYMBOLS = list(dict.fromkeys(NIFTY_500_SYMBOLS + BSE_TOP_SYMBOLS))


def get_static_universe():
    """
    Static fallback universe (NSE + BSE) return karta hai.
    Use when NSE archives / BSE scrip list download fail (cloud block).
    Return: list of {"symbol": "RELIANCE.NS", "name": "", "exchange": "NSE"}
    """
    out = []
    for sym in ALL_SYMBOLS:
        if sym.endswith(".BO"):
            exchange = "BSE"
        else:
            exchange = "NSE"
        out.append({"symbol": sym, "name": "", "exchange": exchange})
    return out


def get_static_symbols():
    """Convenience: sirf symbol list."""
    return list(ALL_SYMBOLS)


# ═══════════════════════════════════════════════════════════════════
# V9.8: EXPANDED UNIVERSE — ALL CAPS (Large + Mid + Small)
# ═══════════════════════════════════════════════════════════════════
# User request: "sabhi stocks scan karna — mid cap, small cap, large cap all"
# Ye list NIFTY 500 + NIFTY MIDCAP 150 + NIFTY SMALLCAP 250 + additional
# liquid NSE stocks contain karti hai (~1000+ stocks).

NIFTY_MIDCAP_150 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "ALKEM.NS", "AMARAJABAT.NS", "AMBUJACEM.NS",
    "APOLLOHOSP.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BATAINDIA.NS", "BERGEPAINT.NS",
    "BIOCON.NS", "BOSCHLTD.NS", "BPCL.NS", "CADILAHC.NS", "CANBK.NS",
    "CHOLAFIN.NS", "COFORGE.NS", "COLPAL.NS", "CONCOR.NS", "COROMANDEL.NS",
    "CUMMINSIND.NS", "DABUR.NS", "DELTACORP.NS", "DEVYANI.NS", "DIXON.NS",
    "DLF.NS", "EICHERMOT.NS", "ESCORTS.NS", "EXIDEIND.NS", "FEDERALBNK.NS",
    "GAIL.NS", "GMRINFRA.NS", "GODREJCP.NS", "GODREJPROP.NS", "GRANULES.NS",
    "GUJGASLTD.NS", "HAVELLS.NS", "HINDPETRO.NS", "HINDZINC.NS", "ICICIGI.NS",
    "ICICIPRULI.NS", "INDHOTEL.NS", "INDIGO.NS", "INDUSTOWER.NS", "IRCTC.NS",
    "JINDALSTEL.NS", "JKCEMENT.NS", "JSWENERGY.NS", "JUBLFOUS.NS", "LALPATHLAB.NS",
    "LAURUSLABS.NS", "LICHFIN.NS", "LODHA.NS", "LUPIN.NS", "M&MFIN.NS",
    "MANAPPURAM.NS", "MARICO.NS", "MCDOWELL-N.NS", "MFSL.NS", "MOTHERSON.NS",
    "MUTHOOTFIN.NS", "NAUKRI.NS", "NMDC.NS", "OBEROIRLTY.NS", "OFSS.NS",
    "PEL.NS", "PERSISTENT.NS", "PETRONET.NS", "PFC.NS", "PIIND.NS",
    "POLYCAB.NS", "PRESTIGE.NS", "PGHH.NS", "RBLBANK.NS", "RECLTD.NS",
    "SAIL.NS", "SFCLTD.NS", "SHREECEM.NS", "SRF.NS", "MANYAVAR.NS",
    "SIEMENS.NS", "Sona.NS", "STARHEALTH.NS", "SUNTV.NS", "SYNGENE.NS",
    "TATAELXSI.NS", "TATACOMM.NS", "TATAINVEST.NS", "TENAGARA.NS", "TRENT.NS",
    "TV18BRDCST.NS", "TVSMOTOR.NS", "UBL.NS", "UCOBANK.NS", "UNIONBANK.NS",
    "UPL.NS", "VBL.NS", "VEDL.NS", "VOLTAS.NS", "WHIRLPOOL.NS",
    "ZYDUSLIFE.NS", "ABFRL.NS", "AARTIIND.NS", "AFFLE.NS", "ANGELONE.NS",
    "ASTRAL.NS", "BALRAMCHIN.NS", "BALKRISIND.NS", "BEPL.NS", "BHEL.NS",
    "BLUEDART.NS", "BSOFT.NS", "CGPOWER.NS", "CDSL.NS", "CLEAN.NS",
    "CRAFTSMAN.NS", "CYIENT.NS", "DBL.NS", "DEEPAKNTR.NS", "EASEMYTRIP.NS",
    "EDELWEISS.NS", "EMAMILTD.NS", "FACT.NS", "FORTIS.NS", "GLENMARK.NS",
    "GMMPHARMA.NS", "GPPL.NS", "GRINFRA.NS", "GSFC.NS", "HEG.NS",
    "HINDCOPPER.NS", "INDIAMART.NS", "INDIANB.NS", "INDUSTOWER.NS", "IOLCP.NS",
    "IPCA.NS", "IRB.NS", "JBMA.NS", "JINDALSAW.NS", "JSL.NS",
    "JUBLINGREA.NS", "JYOTHYLAB.NS", "KPITTECH.NS", "KRISHANA.NS", "LAXMIMACH.NS",
    "MAHSCOOTER.NS", "MAZDOCK.NS", "MCX.NS", "METROBRAND.NS", "MINDTREE.NS",
    "MPSLTD.NS", "NATCOPHARM.NS", "NAVINFLUOR.NS", "NBCC.NS", "NCC.NS",
    "NHPC.NS", "NIACL.NS", "NIITLTD.NS", "NLCINDIA.NS", "OIL.NS",
    "ONGC.NS", "ORIENTELEC.NS", "PAGEIND.NS", "PATANJALI.NS", "PDSMFL.NS",
    "PGHL.NS", "PNCINFRA.NS", "PNBHOUSING.NS", "POLICYBZR.NS", "PRINCEPIPE.NS",
    "QUESS.NS", "RANKLIN.NS", "RATNAMANI.NS", "RVNL.NS", "SAPPHIRE.NS",
    "SCHAEFFLER.NS", "SFL.NS", "SHARDACROP.NS", "SHOPERSTOP.NS", "SJVN.NS",
    "SOLARA.NS", "SONACOMS.NS", "STARCEMENT.NS", "SUDARSCHEM.NS", "SUNDRMFAST.NS",
    "SUNPHARMA.NS", "SUPREMEIND.NS", "SWANENERGY.NS", "SYMPHONY.NS", "TANLA.NS",
    "TATAconsumer.NS", "TATAPOWER.NS", "TATVA.NS", "TCIEXP.NS", "TDPOWER.NS",
    "TIINDIA.NS", "TIPSINDIA.NS", "TORNTPHARM.NS", "TTKPRESTIG.NS", "TVSSCS.NS",
    "UNOMINDA.NS", "VEMRGTECH.NS", "VINATIORGA.NS", "VTL.NS", "WELSPUNLIV.NS",
    "ZENSARTECH.NS", "ZFCVINDIA.NS", "ZOMATO.NS", "NYKAA.NS", "PAYTM.NS",
]

NIFTY_SMALLCAP_250 = [
    "AARTIDRUGS.NS", "AARTIPHARM.NS", "ABINFRA.NS", "ACE.NS", "AEGISCHEM.NS",
    "AIONNRJ.NS", "AJMERA.NS", "AKZOINDIA.NS", "ALEMBICLTD.NS", "ALOKINDS.NS",
    "ALPHAGEO.NS", "AMBER.NS", "ANANTRAJ.NS", "ANDHRACEM.NS", "ANSALAPI.NS",
    "APLLTD.NS", "APTUS.NS", "ARE&M.NS", "ARVINDFAB.NS", "ARVINDSMART.NS",
    "ASAHIINDIA.NS", "ASHOKA.NS", "ASIANELEC.NS", "ASTERDM.NS", "ASTRAZEN.NS",
    "ATUL.NS", "AURIONPRO.NS", "AVANTIFEED.NS", "BAGFILMS.NS", "BALAMINES.NS",
    "BANARBEADS.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS", "BASF.NS",
    "BEML.NS", "BENEFITS.NS", "BIRLACORPN.NS", "BJELECT.NS", "BLKASHYAP.NS",
    "BOMDYEING.NS", "BORORENEW.NS", "BSE.NS", "CARBORUNIV.NS", "CENTRALBK.NS",
    "CENTRUM.NS", "CERA.NS", "CESC.NS", "CGCL.NS", "CHAMBLFERT.NS",
    "CHEMPLASTS.NS", "CHENNPETRO.NS", "CHOLAHLDNG.NS", "CHOLAINV.NS", "CIGNITI.NS",
    "CINELINE.NS", "CITYUNION.NS", "CMRSL.NS", "COCHINSHIP.NS", "COFORGE.NS",
    "CONSOFINVT.NS", "COROMANDEL.NS", "CREATIVEYE.NS", "CREST.NS", "CROSIOL.NS",
    "CRUPHARMA.NS", "CSSL.NS", "CUMMINSIND.NS", "CYBERMEDIA.NS", "DANGEEDUL.NS",
    "DATAPATTNS.NS", "DCAL.NS", "DCBBANK.NS", "DCMHRARAT.NS", "DCMSHRAM.NS",
    "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DELHIVE.NS", "DEN.NS", "DESSO.NS",
    "DHAMPURSUG.NS", "DHANI.NS", "DHARMAJ.NS", "DICIND.NS", "DLF.NS",
    "DNA.NS", "DOLAT.NS", "DOLPHIN.NS", "DONEAR.NS", "DWARIKESH.NS",
    "EASUNREY.NS", "ECLERX.NS", "EIHOTEL.NS", "EIMCOELECO.NS", "ELECON.NS",
    "ELGIEQUIP.NS", "ELGIRLS.NS", "ELXSI.NS", "EMAMILTD.NS", "EMBASSY.NS",
    "ENGINERSIN.NS", "EPL.NS", "EQUITAS.NS", "EQUITASBNK.NS", "ERIS.NS",
    "ESABINDIA.NS", "ESTER.NS", "EUROBOND.NS", "EUROTEX.NS", "EVEXIA.NS",
    "EXIDEIND.NS", "FDC.NS", "FEDERALBNK.NS", "FINEORG.NS", "FINCABLES.NS",
    "FINOPB.NS", "FSL.NS", "FUTURECON.NS", "FUTURELIFE.NS", "FUTUREMD.NS",
    "GEPIL.NS", "GHCL.NS", "GICOFINDIA.NS", "GMRINFRA.NS", "GNFC.NS",
    "GODFRYPHLP.NS", "GODREJAGRO.NS", "GODREJIND.NS", "GOKEX.NS", "GOLDENTOBC.NS",
    "GOGLE.NS", "GOODYEAR.NS", "GRAPHITE.NS", "GRASIM.NS", "GREAVESCOT.NS",
    "GREAVES.NS", "GRINDWELL.NS", "GULFOILLUB.NS", "HAL.NS", "HARIOMATX.NS",
    "HARRMALAYA.NS", "HBLPOWER.NS", "HCL-INSYS.NS", "HEG.NS", "HEIDELBERG.NS",
    "HERITGFOOD.NS", "HIMATSEIDE.NS", "HINDCOMPOS.NS", "HINDNATGLAS.NS", "HINDOILEXP.NS",
    "HINDSYNTEX.NS", "HINDUSTAN.NS", "HMT.NS", "HONAUT.NS", "HOVS.NS",
    "HRINDIA.NS", "HSCL.NS", "ICIL.NS", "IDBI.NS", "IDEA.NS",
    "IDFCFIRSTB.NS", "IFBIND.NS", "IFCI.NS", "IIFL.NS", "IIFLWAM.NS",
    "IITL.NS", "ILL.NS", "IMFA.NS", "INDHOTEL.NS", "INDIACEM.NS",
    "INDIANHUME.NS", "INDIANOIL.NS", "INDORAMA.NS", "INDOSOL.NS", "INDSWFTLTD.NS",
    "INDUSINDBK.NS", "INDUSTOWER.NS", "INFOMEDIA.NS", "INTELLECT.NS", "INTERGRAPH.NS",
    "IPCA.NS", "ITC.NS", "ITI.NS", "J&KBANK.NS", "JAIHIND.NS",
    "JAIRO.NS", "JAMNAAUTO.NS", "JAYAGROGN.NS", "JAYBARM.NS", "JCHAK.NS",
    "JINDALPHHO.NS", "JINDALPOLY.NS", "JINDALSTEL.NS", "JINDSAW.NS", "JKCEMENT.NS",
    "JKLAKSHMI.NS", "JKPAPER.NS", "JKTYRE.NS", "JSL.NS", "JSLHISAR.NS",
    "JUBLINDS.NS", "JYOTI.NS", "JYOTHYLAB.NS", "KABRA.NS", "KARNATAKA.NS",
    "KARURVYSYA.NS", "KEC.NS", "KEI.NS", "KELLTONTEC.NS", "KHADAM.NS",
    "KIRIINDUS.NS", "KIRLOIND.NS", "KIRLOSAR.NS", "KMJM.NS", "KNRCON.NS",
    "KOHINOOR.NS", "KOPRAN.NS", "KOTAKBANK.NS", "KOTHARIPRO.NS", "KOTHARI.NS",
    "KRBL.NS", "KRISHANA.NS", "KSCL.NS", "KSB.NS", "KSCL.NS",
    "KTKBANK.NS", "KTVDMEDIA.NS", "L&TFH.NS", "LAKSHMI.NS", "LAKSHVILAS.NS",
    "LAXMIMACH.NS", "LBORORENEW.NS", "LEMONTREE.NS", "LLOYDSENGG.NS", "LOVABLE.NS",
    "LUMAXIND.NS", "LUXIND.NS", "M&MFIN.NS", "M28.NS", "MAGADSUG.NS",
    "MAHAANAND.NS", "MAHABANK.NS", "MAHASTEEL.NS", "MAHINDCIE.NS", "MAHINDHUG.NS",
    "MAHSCOOTER.NS", "MAHSEAMLES.NS", "MAITHAN.NS", "MANAKALUCO.NS", "MANAKCOAT.NS",
    "MANAPPURAM.NS", "MARALOVER.NS", "MARICO.NS", "MARINE.NS", "MARKSANS.NS",
    "MARRON.NS", "MASC.NS", "MASTEK.NS", "MAHAENT.NS", "MAXHEALTH.NS",
    "MAZDOCK.NS", "MBAPL.NS", "MCDOWELL-N.NS", "MCLEODRUSS.NS", "MCX.NS",
    "MEDANTA.NS", "MEGH.NS", "METROBRAND.NS", "MFL.NS", "MGL.NS",
    "MHHL.NS", "MINDACORP.NS", "MINDAIND.NS", "MINDTREE.NS", "MIRZAINT.NS",
    "MITSUIOSK.NS", "MKEX.NS", "MODIRUBBER.NS", "MODISON.NS", "MOLDTKPAC.NS",
    "MONNET.NS", "MONTECARLO.NS", "MOREPENLAB.NS", "MOTHERSUMI.NS", "MOTILAL.NS",
    "MPSLTD.NS", "MRPL.NS", "MSUMI.NS", "MUKANDLTD.NS", "MUKTAARTS.NS",
    "MUNJAL.NS", "MUTHOOTFIN.NS", "NAGAFERT.NS", "NAGAROIL.NS", "NAGREEKEXP.NS",
    "NATCOPHARM.NS", "NATHBIO.NS", "NATIONALUM.NS", "NAUKRI.NS", "NAVINFLUOR.NS",
    "NAVNETEDU.NS", "NBCC.NS", "NCC.NS", "NDGL.NS", "NECCLTD.NS",
    "NEULAND.NS", "NEWDELHI.NS", "NFCL.NS", "NHPC.NS", "NIFTY.NS",
    "NIACL.NS", "NIITTECH.NS", "NILASPAC.NS", "NIPPOBATR.NS", "NITINSPIN.NS",
    "NLCINDIA.NS", "NNR.NS", "NOIDATOLL.NS", "NORBAN.NS", "NTPC.NS",
    "NUVOCO.NS", "OAL.NS", "OCL.NS", "OCTAVE.NS", "OIL.NS",
    "OKPLAY.NS", "ONGC.NS", "ORIENTBANK.NS", "ORIENTELEC.NS", "ORIENTLTD.NS",
    "ORISSA.NS", "OTTL.NS", "P1.NS", "P2.NS", "P5.NS",
    "PAGEIND.NS", "PAISA.NS", "PANACEABIO.NS", "PANCHS.NS", "PANSARI.NS",
    "PANTALOON.NS", "PARADEEP.NS", "PARAGMILK.NS", "PATANJALI.NS", "PATELENG.NS",
    "PAYTM.NS", "PEL.NS", "PENTA.NS", "PERSISTENT.NS", "PETRONET.NS",
    "PFC.NS", "PFIZER.NS", "PGHL.NS", "PGHH.NS", "PHILIPSCB.NS",
    "PHOENIXLTD.NS", "PIDILITIND.NS", "PIIND.NS", "PNCINFRA.NS", "PNBHOUSING.NS",
    "POLICYBZR.NS", "POLYMED.NS", "POLYCAB.NS", "POLYPLEX.NS", "POWERGRID.NS",
    "PPL.NS", "PRABHAT.NS", "PRAJIND.NS", "PRAKASH.NS", "PRECAM.NS",
    "PRECOT.NS", "PRESTIGE.NS", "PRINCEPIPE.NS", "PRISM.NS", "PRITIKAUTO.NS",
    "PROMUL.NS", "PSB.NS", "PSL.NS", "PSPPROJECT.NS", "PTC.NS",
    "PTCIL.NS", "PUNJABCHEM.NS", "PUNJLLOYD.NS", "PVR.NS", "QUESS.NS",
    "RADAAN.NS", "RADICO.NS", "RADIOCITY.NS", "RAILTEL.NS", "RAINBOW.NS",
    "RAJESH.NS", "RAJRAYON.NS", "RALLIS.NS", "RANKLIN.NS", "RAPID.NS",
    "RATNAMANI.NS", "RAYMOND.NS", "RBLBANK.NS", "RCL.NS", "RECLTD.NS",
    "REDINGTON.NS", "RELHOME.NS", "RELIANCE.NS", "RELINFRA.NS", "RENUKA.NS",
    "RESPONIND.NS", "RIG.NS", "RISAN.NS", "RITES.NS", "RKFORGE.NS",
    "ROCHEX.NS", "ROSSELLIND.NS", "ROLEXRINGS.NS", "RPCL.NS", "RPPL.NS",
    "RTNINDIA.NS", "RUBYMILLS.NS", "RUCHIRA.NS", "RUPA.NS", "RURAL.NS",
    "SABEVENTS.NS", "SADBHAV.NS", "SAFARI.NS", "SAGARCEM.NS", "SAKAR.NS",
    "SAKSOFT.NS", "SALASAR.NS", "SALORA.NS", "SAMIL.NS", "SAMSUNG.NS",
    "SANOFI.NS", "SAPPHIRE.NS", "SASKTL.NS", "SASTASUNDAR.NS", "SBBJ.NS",
    "SBFC.NS", "SCHAEFFLER.NS", "SCHAND.NS", "SCI.NS", "SELANE.NS",
    "SEQUENT.NS", "SETCO.NS", "SFL.NS", "SGL.NS", "SHARDACROP.NS",
    "SHARDAMOTR.NS", "SHEMAROAM.NS", "SHILPAMED.NS", "SHOPERSTOP.NS", "SHREECEM.NS",
    "SHREERAM.NS", "SHYAMCENT.NS", "SHYAMTEL.NS", "SIL.NS", "SILINV.NS",
    "SIMS.NS", "SIRCA.NS", "SIS.NS", "SJVN.NS", "SKFINDIA.NS",
    "SMARTLINK.NS", "SMCGLOBAL.NS", "SOLARA.NS", "SOLARINDS.NS", "SONACOMS.NS",
    "SPANDANA.NS", "SPARC.NS", "SPICEJET.NS", "SRL.NS", "SRTRANSFIN.NS",
    "STARPAPER.NS", "STARHEALTH.NS", "STCINDIA.NS", "STEELXIND.NS", "STERTOOLS.NS",
    "STOVE.NS", "SUDARSCHEM.NS", "SUNCLARLITE.NS", "SUNDARMFIN.NS", "SUNDARMHLD.NS",
    "SUNDRMFAST.NS", "SUNPHARMA.NS", "SUNTECK.NS", "SUNTV.NS", "SUPERCASH.NS",
    "SUPERHOUSE.NS", "SUPREMEIND.NS", "SUVENPHAR.NS", "SWANENERGY.NS", "SWARAJENG.NS",
    "SWELECTES.NS", "SYMPHONY.NS", "SYNGENE.NS", "TABCAPITAL.NS", "TALBROAUTO.NS",
    "TANLA.NS", "TASTYBITE.NS", "TATAchemical.NS", "TATACOFFEE.NS", "TATACOMM.NS",
    "TATAELXSI.NS", "TATAINVEST.NS", "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS",
    "TATAconsumer.NS", "TCIEXP.NS", "TCNSBRANDS.NS", "TDPOWER.NS", "TEAMLEASE.NS",
    "TECHM.NS", "TEJASNET.NS", "TENAGARA.NS", "TERAOIL.NS", "TEXMO.NS",
    "TEXRAILS.NS", "THANGAMUG.NS", "THOMASCOOK.NS", "THYROCARE.NS", "TIINDIA.NS",
    "TIPSINDIA.NS", "TIRUPATIFL.NS", "TITAGARH.NS", "TITAN.NS", "TORNTPHARM.NS",
    "TRENT.NS", "TRIDENT.NS", "TRIGYN.NS", "TTKPRESTIG.NS", "TV18BRDCST.NS",
    "TVSSCS.NS", "TVSMOTOR.NS", "UBL.NS", "UCOBANK.NS", "UFLEX.NS",
    "UGROCAP.NS", "ULTRACEMCO.NS", "UNICHIPLS.NS", "UNIENTER.NS", "UNIONBANK.NS",
    "UNITDSPR.NS", "UNIVCABLES.NS", "UPL.NS", "UTI.NS", "UTTAM.NS",
    "UTTAMSUG.NS", "VBL.NS", "VEDL.NS", "VEDIT.NS", "VENKEYS.NS",
    "VERANDA.NS", "VESUVIUS.NS", "VGUARD.NS", "VHL.NS", "VIDHIING.NS",
    "VIMTA.NS", "VINATIORGA.NS", "VIPCLOTHNG.NS", "VIRINCHI.NS", "VISESHINFO.NS",
    "VSTIND.NS", "VTL.NS", "VTLTIL.NS", "VTLTD.NS", "VTPETS.NS",
    "WABAG.NS", "WELCORP.NS", "WELSPUNIND.NS", "WELSPUNLIV.NS", "WESTLIFE.NS",
    "WHIRLPOOL.NS", "WINDLAS.NS", "WIPRO.NS", "WOCKPHARMA.NS", "XCHANGING.NS",
    "XLENE.NS", "XLINV.NS", "XPROINDIA.NS", "YAARI.NS", "YATR.NS",
    "YUKEN.NS", "ZENSARTECH.NS", "ZENTEC.NS", "ZFCVINDIA.NS", "ZODIACLOTH.NS",
    "ZOMATO.NS", "ZUARI.NS", "ZUARIGLOB.NS", "ZYDUSWELL.NS", "NYKAA.NS",
]

# V9.8: Combined ALL CAPS universe
ALL_CAPS_UNIVERSE = list(dict.fromkeys(
    NIFTY_500_SYMBOLS + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250 + BSE_TOP_SYMBOLS
))

# Override ALL_SYMBOLS with expanded list
ALL_SYMBOLS = ALL_CAPS_UNIVERSE
