"""
===========================================================
 STATIC STOCK UNIVERSE FALLBACK (V8.3.3)
===========================================================
Cloud (Render) par NSE archives (ind_nifty500list.csv,
EQUITY_L.csv) BLOCK ho jaate hain (403). Isliye jab
universe_fetcher.py ko live list nahi mil paati, to ye
STATIC list fallback ke roop mein use hoti hai.

Ye list NIFTY 500 (top 500 NSE stocks by market cap) +
top ~100 BSE stocks contain karti hai — manually curated,
publicly available NSE/BSE constituents se.

Update karna ho to: NSE website se NIFTY 500 list download
karke neeche SYMBOLS list mein add/remove kar do.
===========================================================
"""

# NIFTY 500 constituents (NSE top 500 by market cap, .NS suffix)
# Source: NSE india official NIFTY 500 list (manually embedded as
# static fallback since NSE archives blocks cloud IPs).
NIFTY_500_SYMBOLS = [
    # --- Top 100 (NIFTY 100) ---
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "ITC.NS", "BHARTIARTL.NS", "LT.NS",
    "KOTAKBANK.NS", "Bajfinance".upper()+".NS", "ASIANPAINT.NS", "MARUTI.NS", "HCLTECH.NS",
    "AXISBANK.NS", "WIPRO.NS", "ONGC.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS",
    "TITAN.NS", "NESTLEIND.NS", "TATAMOTORS.NS", "POWERGRID.NS", "BAJFINANCE.NS",
    "NTPC.NS", "ADANIGREEN.NS", "TECHM.NS", "ADANIPORTS.NS", "HDFCLIFE.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "DIVISLAB.NS", "GRASIM.NS", "CIPLA.NS",
    "BAJAJFINSV.NS", "COALINDIA.NS", "BRITANNIA.NS", "BPCL.NS", "HEROMOTOCO.NS",
    "SHRIRAMFIN.NS", "EICHERMOT.NS", "TATACONSUM.NS", "M&M.NS", "ADANIENT.NS",
    "DABUR.NS", "INDUSINDBK.NS", "SBILIFE.NS", "HINDALCO.NS", "DRREDDY.NS",
    "BAJAJ-AUTO.NS", "TATACONSUM.NS", "GAIL.NS", "IOC.NS", "TATAPOWER.NS",
    "HDFCAMC.NS", "AMBUJACEM.NS", "ACC.NS", "PIDILITIND.NS", "ZOMATO.NS",
    "SIEMENS.NS", "ABB.NS", "PNB.NS", "BANKBARODA.NS", "CANBK.NS",
    "DLF.NS", "GODREJCP.NS", "COLPAL.NS", "MARICO.NS", "HAVELLS.NS",
    "MUTHOOTFIN.NS", "BOSCHLTD.NS", "VEDL.NS", "LODHA.NS", "HAL.NS",
    "BEL.NS", "BHEL.NS", "NMDC.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "MCDOWELL-N.NS", "INDIGO.NS", "TORNTPHARM.NS", "UNITDSPR.NS", "SAIL.NS",
    "JINDALSTEL.NS", "MOTHERSON.NS", "BHARATFORG.NS", "BANDHANBNK.NS", "LUPIN.NS",
    "AUROPHARMA.NS", "BIOCON.NS", "MANAPPURAM.NS", "TVSMOTOR.NS", "PERSISTENT.NS",
    # --- NIFTY 100-200 ---
    "DMART.NS", "ZEE.NS", "PFC.NS", "RECLTD.NS", "MRF.NS",
    "APOLLOHOSP.NS", "BERGEPAINT.NS", "TRENT.NS", "UNIONBANK.NS", "SBICARDS.NS",
    "INDUSTOWER.NS", "GMRINFRA.NS", "M&MFIN.NS", "CHOLAFIN.NS", "ASHOKLEY.NS",
    "IDEA.NS", "YESBANK.NS", "IRCTC.NS", "NAUKRI.NS", "FEDERALBNK.NS",
    "MPHASIS.NS", "OFSS.NS", "LTI.NS", "LTTS.NS", "COFORGE.NS",
    "BATAINDIA.NS", "CONCOR.NS", "INDHOTEL.NS", "JUBLFOOD.NS", "DEVYANI.NS",
    "BANKINDIA.NS", "MAHABANK.NS", "INDIANB.NS", "CANFINHOME.NS", "LICHFIN.NS",
    "PEL.NS", "SRF.NS", "PIIND.NS", "UPL.NS", "COROMANDEL.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "AMARAJABAT.NS", "SONACOMS.NS", "POLYCAB.NS",
    "CUMMINSIND.NS", "CGPOWER.NS", "KPITTECH.NS", "CDSL.NS", "BSE.NS",
    "ANGELONE.NS", "ICICISECURS.NS", "HDFCSEC.NS", "MOTILALOFS.NS", "UTIBANKC.NS",
    # --- NIFTY 200-500 (large + mid cap) ---
    "AUBANK.NS", "RBLBANK.NS", "FEDERALBNK.NS", "KARURVYSYA.NS", "JKBANK.NS",
    "SUPREMEIND.NS", "ASTRAL.NS", "PRINCEPIPE.NS", "MASTEK.NS", "TATAELXSI.NS",
    "QUESS.NS", "RVNL.NS", "IRFC.NS", "NBCC.NS", "HUDCO.NS",
    "INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM",
    "MINDTREE.NS", "OFSS.NS", "MPHASIS.NS", "SONATSOFTW.NS", "TATAELXSI.NS",
    "AFFLE.NS", "INDIAMART.NS", "NAUKRI.NS", "JUSTDIAL.NS", "INDUSTOWER.NS",
    "BHARTIHEXA.NS", "INDUSTOW.NS", "TATAINVEST.NS", "BAJAJHLDNG.NS", "ADANIPOWER.NS",
    "ADANITRANS.NS", "ADANIGAS.NS", "ADANIWILMAR.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "JSWENERGY.NS", "JSWSTEEL.NS", "JSWLIVE.NS", "JSL.NS", "JINDALSTEL.NS",
    "SAIL.NS", "TATASTEEL.NS", "NSSMC.NS", "VISA.NS", "NMDC.NS",
    "NATIONALUM.NS", "HINDZINC.NS", "HINDCOPPER.NS", "NALCO.NS", "GMRAIRPORT.NS",
    "GMRINFRA.NS", "GAIL.NS", "GUJGASLTD.NS", "IGL.NS", "MGL.NS",
    "PETRONET.NS", "AEGISCHEM.NS", "ATUL.NS", "DEEPAKNTR.NS", "NAVINFLUOR.NS",
    "TATACHEM.NS", "PIIND.NS", "UPL.NS", "COROMANDEL.NS", "FACT.NS",
    "SFCLTD.NS", "RAMCOCEM.NS", "ULTRACEMCO.NS", "GRASIM.NS", "AMBUJACEM.NS",
    "ACC.NS", "SHREECEM.NS", "DALBHARAT.NS", "HEIDELBERG.NS", "PRISMJOHN.NS",
    "JKCEMENT.NS", "STARCEMENT.NS", "ORIENTCEM.NS", "INDIACEM.NS", "DHANI.NS",
    "PHOENIXLTD.NS", "OBEROIRLTY.NS", "LODHA.NS", "PRESTIGE.NS", "GODREJPROP.NS",
    "BRIGADE.NS", "SOBHA.NS", "MAHLIFE.NS", "DLF.NS", "INDIABULLS.NS",
    "DHFL.NS", "CANFINHOME.NS", "LICHFIN.NS", "PNBHOUSING.NS", "AEGISCHEM.NS",
    "BAJAJHLDNG.NS", "BANDHANBNK.NS", "RBLBANK.NS", "FEDERALBNK.NS", "KARURVYSYA.NS",
    "IDFCFIRSTB.NS", "J&KBANK.NS", "KARNATAKA.NS", "TAMILNADU.NS", "DCBBANK.NS",
    "CITYUNION.NS", "SOUTHINDIA.NS", "BANKOFMAH.NS", "PSB.NS", "UCOBANK.NS",
    "IOB.NS", "CENTRALBK.NS", "DENABANK.NS", "ANDHRABANK.NS", "ALLAHABANK.NS",
    "PNB.NS", "BANKOFBARODA.NS", "UNIONBANKOFINDIA.NS", "CANARABANK.NS", "SYNDICATEBANK.NS",
    # --- Pharma / Healthcare ---
    "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "LUPIN.NS",
    "AUROPHARMA.NS", "BIOCON.NS", "TORNTPHARM.NS", "ABBOTINDIA.NS", "GLENMARK.NS",
    "ALKEM.NS", "IPCA.NS", "CADILAHC.NS", "WOCKPHARMA.NS", "SHILPAMED.NS",
    "LAURUSLABS.NS", "AJANTPHARM.NS", "JBCHMICALS.NS", "CAPLI.NS", "SYNGENE.NS",
    "SANOFI.NS", "PFIZER.NS", "NOVARTIS.NS", "GLAXO.NS", "MERCK.NS",
    "APLLTD.NS", "ECLERX.NS", "HCG.NS", "FORTIS.NS", "APOLLOHOSP.NS",
    "RAINBOW.NS", "GLOBALHIT.NS", "THYROCARE.NS", "METROPOLIS.NS", "DRPATHLAB.NS",
    # --- FMCG / Consumer ---
    "HINDUNILVR.NS", "NESTLEIND.NS", "BRITANNIA.NS", "ITC.NS", "DABUR.NS",
    "GODREJCP.NS", "MARICO.NS", "COLPAL.NS", "TATACONSUM.NS", "VSTIND.NS",
    "PGHH.NS", "EMAMILTD.NS", "BAJAJELEC.NS", "TTKPRESTIG.NS", "HAVELLS.NS",
    "SYMPHONY.NS", "AMBANI.NS", "VOLTAS.NS", "BLUECOAST.NS", "WHIRLPOOL.NS",
    # --- Auto / Auto Ancillary ---
    "MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "BAJAJ-AUTO.NS", "TVSMOTOR.NS", "ASHOKLEY.NS", "ESCORTS.NS", "BALKRISIND.NS",
    "BOSCHLTD.NS", "MOTHERSON.NS", "BHARATFORG.NS", "MUNJAL.NS", "ENDURANCE.NS",
    "SUPRAJIT.NS", "SUBROS.NS", "GABRIEL.NS", "AUTOLITIND.NS", "WABCOINDIA.NS",
    # --- IT / Tech ---
    "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS",
    "LTIM.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS", "OFSS.NS",
    "TATAELXSI.NS", "LTTS.NS", "SONATSOFTW.NS", "KPITTECH.NS", "MASTEK.NS",
    "AFFLE.NS", "INDIAMART.NS", "NAUKRI.NS", "JUSTDIAL.NS", "MAPMYINDIA.NS",
    "TANLA.NS", "ROUTE.NS", "EXPLEO.NS", "KELLTONTEC.NS", "VELAN.NS",
    # --- Energy / Power / Oil ---
    "RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "IOC.NS",
    "BPCL.NS", "HPCL.NS", "GAIL.NS", "PETRONET.NS", "ONGC.NS",
    "OIL.NS", "COALINDIA.NS", "NHPC.NS", "SJVN.NS", "NLCINDIA.NS",
    "TATAPOWER.NS", "ADANIPOWER.NS", "ADANIGREEN.NS", "JSWENERGY.NS", "THERMAX.NS",
    "ABBOTINDIA.NS", "BEL.NS", "BHEL.NS", "CGPOWER.NS", "CUMMINSIND.NS",
    # --- Metals / Mining ---
    "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "SAIL.NS",
    "JINDALSTEL.NS", "NMDC.NS", "HINDZINC.NS", "NALCO.NS", "NATIONALUM.NS",
    "JSPL.NS", "APLAPOLLO.NS", "RATNAMANI.NS", "MAHASTEEL.NS", "UTTAMSTL.NS",
    # --- Real Estate / Infra ---
    "DLF.NS", "LODHA.NS", "OBEROIRLTY.NS", "GODREJPROP.NS", "PRESTIGE.NS",
    "BRIGADE.NS", "SOBHA.NS", "PHOENIXLTD.NS", "NBCC.NS", "IRB.NS",
    "PNCINFRA.NS", "KNRCON.NS", "HGINFRA.NS", "GRINFRA.NS", "SADBHAV.NS",
    "ASTRAL.NS", "PRINCEPIPE.NS", "SUPREMEIND.NS", "MAHAVENT.NS", "WELSHPUNJ.NS",
    # --- Telecom / Media ---
    "BHARTIARTL.NS", "IDEA.NS", "INDUSTOWER.NS", "TATACOMM.NS", "BHARTIHEXA.NS",
    "ZEE.NS", "SUNTV.NS", "TV18BRDCST.NS", "PVR.NS", "INOXLEISUR.NS",
    "TIPSIND.NS", "MUSICBROADCAST.NS", "NETWORK18.NS", "NIITLTD.NS", "HUNGAMA.NS",
]

# BSE top liquid stocks (.BO suffix) — BSE Group A stocks, top by volume
BSE_TOP_SYMBOLS = [
    "RELIANCE.BO", "TCS.BO", "INFY.BO", "HDFCBANK.BO", "ICICIBANK.BO",
    "SBIN.BO", "ITC.BO", "BHARTIARTL.BO", "LT.BO", "HINDUNILVR.BO",
    "TATAMOTORS.BO", "WIPRO.BO", "AXISBANK.BO", "MARUTI.BO", "ASIANPAINT.BO",
    "TATASTEEL.BO", "SUNPHARMA.BO", "ULTRACEMCO.BO", "TITAN.BO", "NESTLEIND.BO",
    "POWERGRID.BO", "NTPC.BO", "TECHM.BO", "GRASIM.BO", "HCLTECH.BO",
    "ONGC.BO", "COALINDIA.BO", "BPCL.BO", "IOC.BO", "JSWSTEEL.BO",
    "HINDALCO.BO", "VEDL.BO", "SAIL.BO", "GAIL.BO", "HEROMOTOCO.BO",
    "EICHERMOT.BO", "M&M.BO", "BAJAJ-AUTO.BO", "BAJFINANCE.BO", "BAJAJFINSV.BO",
    "ADANIPORTS.BO", "ADANIENT.BO", "ADANIGREEN.BO", "DMART.BO", "ZOMATO.BO",
    "PIDILITIND.BO", "DABUR.BO", "GODREJCP.BO", "MARICO.BO", "COLPAL.BO",
    "SIEMENS.BO", "ABB.BO", "BEL.BO", "BHEL.BO", "HAL.BO",
    "PNB.BO", "BANKBARODA.BO", "CANBK.BO", "UNIONBANK.BO", "IDFCFIRSTB.BO",
    "YESBANK.BO", "RBLBANK.BO", "FEDERALBNK.BO", "AUBANK.BO", "BANDHANBNK.BO",
]

# Combined unified list (deduplicated)
ALL_SYMBOLS = list(dict.fromkeys(NIFTY_500_SYMBOLS + BSE_TOP_SYMBOLS))


def get_static_universe():
    """
    Static fallback universe (NSE + BSE) return karta hai.
    Use when NSE archives / BSE scrip list download fail (cloud block).
    Return: list of {"symbol": "RELIANCE.NS", "name": "", "exchange": "NSE"}
    """
    out = []
    for sym in ALL_SYMBOLS:
        if sym.endswith(".BO"):
            exchange = "BSE"
        else:
            exchange = "NSE"
        out.append({"symbol": sym, "name": "", "exchange": exchange})
    return out


def get_static_symbols():
    """Convenience: sirf symbol list."""
    return list(ALL_SYMBOLS)
